src/api/index.js, src/components/Account/Wishlist/GridGames/GridGames.js, src/components/Account/Wishlist/GridGames/GridGames.module.scss, src/components/Account/Wishlist/GridGames/index.js, src/components/Account/Wishlist/Wishlist.js, src/components/Account/Wishlist/index.js, src/components/Account/index.js, src/components/Shared/Label/Discount/Discount.js, src/components/Shared/Label/Discount/Discount.module.scss, src/components/Shared/Label/Discount/index.js, src/components/Shared/Label/index.js, src/components/Shared/NoResult/NoResult.js, src/components/Shared/NoResult/NoResult.module.scss, src/components/Shared/NoResult/index.js, src/components/index.js, src/pages/account/account.js, src/pages/account/account.module.scss, src/pages/account/index.js, src/utils/functions/calcDiscountedPrice.js, src/utils/functions/index.js
Lógica add games.
Lógica delete game.
Añadiendo wishlist.
Grid de la lista.
Icono para quitar de la lista de deseos.
=> add-delete-grid-icons-wishlist

.gitignore, src/layouts/JoinLayout/JoinLayout.js, src/layouts/JoinLayout/JoinLayout.module.scss, src/layouts/JoinLayout/index.js, src/layouts/index.js, src/pages/index.js, src/pages/join/sign-in/index.js, src/pages/join/sign-in/sign-in.js, src/pages/join/sign-up/index.js, src/pages/join/sign-up/sign-up.js, src/scss/colors.scss, src/scss/global.scss, src/scss/index.scss, src/scss/semantic-ui/buttom.scss, src/scss/semantic-ui/index.scss
baje desde develop y subi todo lo que hice desde el comienzo
=> styles y sign-in primeros pasos

package.json, src/api/auth.js, src/api/index.js, src/components/Auth/LoginForm/LoginForm.form.js, src/components/Auth/LoginForm/LoginForm.js, src/components/Auth/LoginForm/index.js, src/components/Auth/RegisterForm/RegisterForm.form.js, src/components/Auth/RegisterForm/RegisterForm.js, src/components/Auth/RegisterForm/index.js, src/components/Auth/index.js, src/layouts/JoinLayout/JoinLayout.js, src/layouts/JoinLayout/JoinLayout.module.scss, src/pages/_app.js, src/pages/index.js, src/pages/join/sign-in/sign-in.js, src/pages/join/sign-in/sign-in.module.scss, src/pages/join/sign-up/sign-up.js, src/pages/join/sign-up/sign-up.module.scss, src/scss/semantic-ui/form.scss, src/scss/semantic-ui/index.scss
=> register form ok

src/components/Layout/TopBar/TopBar.js, src/components/Layout/TopBar/TopBar.module.scss, src/components/Layout/TopBar/index.js, src/components/Layout/index.js, src/layouts/BasicLayout/BasicLayout.js, src/layouts/BasicLayout/BasicLayout.module.scss, src/layouts/BasicLayout/index.js, src/layouts/index.js, src/pages/home/home.js, src/pages/home/index.js
Layout principal
BasicLayout - Home - TopBar - Footer
Estructura TopBar
logo - Menu - Account
=> Layout-ppal-home-topbar

src/api/token.js, src/api/user.js, src/layouts/JoinLayout/JoinLayout.js, src/pages/index.js, src/utils/authFetch.js
logica de sesion de usuario ok
=> logica de sesion ok

src/api/game.js, src/components/Dashboard/Games/GameForm/GameForm.form.js
=> fix(validations)

package.json, src/components/Auth/LoginForm/LoginForm.js, src/components/Auth/RegisterForm/RegisterForm.js, src/pages/join/sign-in/sign-in.js, yarn.lock
=> autenticacion con Google

src/components/Dashboard/Games/GameForm/GameForm.form.js
modificacion del manejo de errores en creacion de games,input title para que acepte letras y numeros.
=> regext title

src/components/Shared/GridGames/GridGames.js, src/components/Shared/GridGames/GridGames.module.scss
=> grid games

src/components/Dashboard/Games/GameForm/GameForm.js
arreglado la actualizacion de imagenes del juego
arreglado el bug de seleccionar id de plataforma siempre
arreglado que no permita subir archivos que no sean imagens
=> fix(updategame)

src/components/Game/Panel/Panel.js
se agrega un ternario para q muestre el stock
=> ternario con y sin stock

src/api/review.js, src/components/Account/Orders/Order/reviewForm/ReviewForm.Form.js, src/components/Account/Orders/Order/reviewForm/ReviewForm.js, src/components/Account/Orders/Order/reviewForm/reviewForm.module.scss
=> iconos en form de review

src/pages/404.js, src/pages/404.module.scss, src/pages/[game]/game.js, src/pages/[game]/index.js
Need aprobación please is the basic page 404.
Le falta mejorar estilo pero ya funciona gracias a la valiosa ayuda del Leo!!!!
=> page-404.v1 basic

src/pages/404.js, src/pages/404.module.scss
Mejora estilización página 404.
=> page-404 v.2

src/components/Account/Orders/Order/reviewForm/ReviewForm.js, src/components/Account/Orders/Order/reviewForm/reviewForm.module.scss
=> cambio de estylos en form review

src/api/order.js, src/components/Account/Sales/Sale/Sale.js, src/components/Account/Sales/Sale/Sale.module.scss, src/components/Account/Sales/Sale/index.js, src/components/Account/Sales/Sales.js, src/components/Account/Sales/Sales.module.scss, src/components/Account/Sales/index.js, src/components/Account/index.js, src/pages/account/account.js
Panel de administrador: Si está logeado como admin solo Muestra solo Ventas, Usuarios y Juegos
Se crea componente de ventas con paginación y filtros de ventas por fechas y total de ventas en el periodo seleccionado.
=> ComponenteVentas

src/api/game.js, src/components/Dashboard/Games/ListGames/Game/Game.js, src/components/Dashboard/Games/ListGames/Game/Game.module.scss, src/components/Dashboard/Games/ListGames/ListGames.js
Borrado Lógico en el panel de admin, se elimina la opción de borrar **(X)** videojuegos y se cambia por "Publicar" o "Despublicar" juegos con un _checkbox toggle_
=> unpublisedGames

src/components/Home/BannerLastGamePublished/BannerLastGamePublished.js, src/components/Home/BannerLastGamePublished/BannerLastGamePublished.module.scss, src/pages/account/account.js
-Sacar boton Crear a Usuario.
-Pag ppal en el nombre del juego difuminarlo.
-En sign-up arreglar estilo row2.
=> subliminacion boton crear usuario y styles form login

src/components/Auth/LoginForm/LoginForm.js, src/components/Auth/RegisterForm/RegisterForm.js, src/pages/join/sign-up/sign-up.js, src/utils/translateError.js
validacion de error en login y register form
=> validacion de error en login y register form

next.config.js, package.json, src/scss/global.scss, src/utils/constants.js
"responsive-app-global-scss-minimum 500px"
Modificación responsive global.
=> responsive-app-global-scss-minimum 500px

src/components/Chatbot/Chatbot.js, src/components/Chatbot/Chatbot.module.scss, src/pages/[game]/game.js, src/pages/search/search.js, src/utils/constants.js
Chatbot:
Agregado en detail game y search.
Input component inhabilitado, submit icon eliminado
Se cierra automáticamente cuando redirecciona tanto a descuentos como a home
Font type cambiada Lato
=> Lubazuliani

src/api/users.js, src/components/Account/Sales/Sales.js, src/components/Users/ListUsers/User/User.js, src/pages/account/account.js
- Cambiar nombre de "Dashboard" a "Video Games" en barra de opciones de admin:
- Orden fijo (Alfabético por nombre de usuario) en el dashboard del admin opción "Usuarios" para que al inactivar un usuario no se vaya al final (pareciendo que desaparece).
- Al presionar el botón de bloqueo se pone "gris" para que se note la diferencia al bloquear.
- Ajustes al filtrado de ventas según fechas.
=> Algunos ajustes en Dashboard

src/components/Layout/Footer/Footer.module.scss, src/pages/home/home.js, src/pages/home/home.module.scss
@media screen and (max-width:550px) {
.containerd{
width: 120%;
}
} con esto ajustamos las medidas de los componentes del home para que lleguen de extremo a extremo
=> home responsive

src/components/Layout/Footer/Footer.js, src/utils/constants.js
=> fix-contacto-footer

src/components/Auth/RegisterForm/RegisterForm.form.js
=> reparacion form register
